apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dev-env-defaultvalues
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-env.labels" . | nindent 4 }} 
data:
  default-values.yaml: |
    service:
      type: ClusterIP
