apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:  
  name: test
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}  
spec:
  chart:
    spec:
      chart: test
      sourceRef:
        kind: HelmRepository
        name: "{{ .Release.Namespace }}-test"
        namespace: {{ .Release.Namespace }}
      version: 0.1.0
  interval: 1m0s
  releaseName: test
  valuesFrom:
  - kind: ConfigMap
    name: dev-env-defaultvalues
    valuesKey: default-values.yaml
status: {}