apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:  
  name: "{{ .Release.Namespace }}-test"
  namespace: {{ .Release.Namespace }}
spec:
  interval: 0s
  url: https://owainperry.github.io/helm-charts
status: {}