apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init-scripts-config
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}    
data:
  run.sh: |+
    #!/bin/sh
    set -xe
    export AWS_ACCESS_KEY_ID=foo
    export AWS_SECRET_ACCESS_KEY=bar
    export AWS_DEFAULT_REGION=us-east-2
    AWS_REGION=$AWS_DEFAULT_REGION
    SNS_PORT=4566
    SQS_PORT=4566
    HOST=localstack

