apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: localstack
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}    
spec:
  interval: 5m
  url: https://localstack.github.io/helm-charts 