apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localstack
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}    
spec:
  releaseName: localstack
  interval: 1m0s
  #serviceAccountName: default
  chart:
    spec:
      chart: localstack
      sourceRef:
        kind: HelmRepository
        name: "localstack"
        namespace: {{ .Release.Namespace }}
      version: 0.3.7  
  valuesFrom:
  - kind: ConfigMap
    name: localstack-defaultvalues
    valuesKey: default-values.yaml