apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:  
  name: "{{ .Release.Namespace }}-vault"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}   
spec:
  interval: 0s
  url: https://helm.releases.hashicorp.com
status: {}