apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:  
  name: vault
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}  
spec:
  releaseName: vault
  interval: 1m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: "{{ .Release.Namespace }}-vault"
        namespace: {{ .Release.Namespace }}
      version: 0.18.0
  valuesFrom:
  - kind: ConfigMap
    name: "{{ .Release.Namespace }}-vault"
    valuesKey: default-values.yaml
status: {}